In [1]:
# import numpy as np
import numpy as np


In [2]:
# creating numpy arrays directly

## 1-d array
a=np.array([1,4.5,True])  

## 2-d array
b=np.array([[2,3,6],[8,9.5,False]]) 

## 2-d array
c=np.array([(9.2,8.6,7.0),(1.1,4,5)])  

In [4]:
a

array([ 1. ,  4.5,  1. ])

In [5]:
b

array([[ 2. ,  3. ,  6. ],
       [ 8. ,  9.5,  0. ]])

In [6]:
c

array([[ 9.2,  8.6,  7. ],
       [ 1.1,  4. ,  5. ]])

In [7]:
# creating numpy array from np.zeros()

# row of 5 zeros  of default float type
d=np.zeros(5)   

# row of 5 zeros  of int type
e=np.zeros(5,dtype=np.int)   

# row=2,col.=3
f=np.zeros((2,3))   

In [8]:
d

array([ 0.,  0.,  0.,  0.,  0.])

In [9]:
e

array([0, 0, 0, 0, 0])

In [10]:
f

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
# creating numpy array from np.ones()

# row of 5 ones  of default float type
g=np.ones(5) 

#row of 5 ones of complex type
h=np.ones(5,dtype=np.complex) 

# row =3,col.=2
i=np.ones((3,2),dtype=float)   

In [12]:
g

array([ 1.,  1.,  1.,  1.,  1.])

In [13]:
h

array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j])

In [14]:
i

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [15]:
# creating numpy arrays from np.arange()
j=np.arange(0,5,1,dtype=np.int)

# defaults start=0,step-size=1
k=np.arange(5)      

In [16]:
j

array([0, 1, 2, 3, 4])

In [17]:
k

array([0, 1, 2, 3, 4])

In [18]:
# creating numpy arrays from np.linspace()

 #parameters are start,end,no.of elements
l=np.linspace(3,8,10)

In [19]:
l

array([ 3.        ,  3.55555556,  4.11111111,  4.66666667,  5.22222222,
        5.77777778,  6.33333333,  6.88888889,  7.44444444,  8.        ])

In [20]:
# creating numpy arrays from np.full()
m=np.full((3,2),5.6)

In [21]:
m

array([[ 5.6,  5.6],
       [ 5.6,  5.6],
       [ 5.6,  5.6]])

In [22]:
# creating numpy array from np.random.random()
## random values are always float type onle no dtype argument available
n=np.random.random(5)
o=np.random.random((2,3))

In [23]:
n

array([ 0.07576793,  0.81886471,  0.8228421 ,  0.19275071,  0.86328123])

In [24]:
n

array([ 0.07576793,  0.81886471,  0.8228421 ,  0.19275071,  0.86328123])